typography_spectrum: 0.3524814457632601
color:
  brandStrength: 0.4231620328500867
  lightness: 0.6129731717519462
  saturation: 0.799912994960323
  rhythmicContrast: 0.572964679915458
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
layout_spectrum: 0.8880974208004773
author:
  name: Lazaro A Sanchez
  email: laz@covenantdevelopment.us
  url: 'http://www.covenantdevelopment.us/ '
name: Inside the Box thinking...
title: ISBU Container Structures
description: 'www.mymoderncontainer.house '
